from __future__ import annotations

from functools import cache

from schubmult.combinatorics.rc_graph import RCGraph
from schubmult.rings.base_ring import BaseRing, BaseRingElement
from schubmult.rings.combinatorial.bounded_rc_factor_algebra import (
    BoundedRCFactorAlgebra,
)
from schubmult.rings.combinatorial.rc_graph_ring import RCGraphRing
from schubmult.rings.printing import PrintingTerm, TypedPrintingTerm
from schubmult.symbolic import S


class PhantomQuotientPrintingTerm(PrintingTerm):
    """Printing term for phantom quotient elements.

    Displays the squashed RC graph (what the tensor key evaluates to),
    wrapped in brackets [⋅] to indicate it lives in the quotient.
    The underlying tensor factorization is shown via the factor algebra
    printing when needed.
    """

    is_commutative = False
    precedence = 50

    def __new__(cls, key, rc):
        return PhantomQuotientPrintingTerm.__xnew_cached__(cls, key, rc)

    @staticmethod
    def __xnew__(_class, key, rc):
        obj = PrintingTerm.__new__(_class, key, None, None)
        obj._key = key
        obj._rc = rc
        return obj

    @staticmethod
    def __xnew_cached__(_class, key, rc):
        return PhantomQuotientPrintingTerm.__xnew__(_class, key, rc)

    def __hash__(self):
        return hash((self._key, "PhantomQuotientPrintingTerm"))

    def _sympystr(self, printer):
        if len(self._key) == 0:
            return printer._print(S.One)
        rc_str = printer._print(TypedPrintingTerm(self._rc))
        return f"[{rc_str}]"

    def _pretty(self, printer):
        if len(self._key) == 0:
            return printer._print(S.One)
        from sympy.printing.pretty.stringpict import prettyForm
        rc_pretty = printer._print(TypedPrintingTerm(self._rc))
        return prettyForm(*rc_pretty.parens("[", "]"))

    def _latex(self, printer):
        if len(self._key) == 0:
            return printer._print(S.One)
        rc_latex = printer._print(TypedPrintingTerm(self._rc))
        return r"\left[" + rc_latex + r"\right]"


class PhantomQuotientElement(BaseRingElement):
    """Element of BRC / I, where I is the two-sided ideal generated by phantom CEM differences.

    Stored as {_key: coeff} in the factor algebra basis, reduced modulo
    the phantom generators. Note: generator reduction is NOT the same as
    full ideal reduction — products a*g*b of generators with arbitrary
    elements produce new ideal elements that still vanish at the polynomial
    (weight) level but may be nonzero at the RC graph level.
    """

    def as_ordered_terms(self, *_, **__):
        if len(self.keys()) == 0:
            return [S.Zero]
        return [self[k] if k == self.ring.zero_monom else self[k] * self.ring.printing_term(k) for k in self.keys()]

    def to_rc_graph_ring_element(self):
        r = RCGraphRing()
        result = r.zero
        for key, coeff in self.items():
            if coeff == 0:
                continue
            rc = self.ring.brc.key_to_rc_graph(key)
            result += coeff * r(rc)
        return result

    def weight_vanishing_component(self):
        """Decompose this element into weight-surviving and weight-vanishing parts.

        Returns (surviving, vanishing) where:
          surviving = reduce(self) — the part with well-defined weight
          vanishing = self - surviving — the part that vanishes in weight,
                      which lies in the ideal (or at least ker(weight_map))
        """
        surviving = self.ring.reduce(self)
        vanishing = self.ring.sub(self, surviving)
        return surviving, vanishing


class PhantomQuotientAlgebra(BaseRing):
    """Quotient of BoundedRCFactorAlgebra by the two-sided ideal I generated
    by phantom CEM differences.

    For permutation w at size n, the CEM expansion of S_w may include tensor
    monomials that squash to RC graphs for a DIFFERENT permutation w' != w.
    For each such phantom RC graph R, the tensor monomials that contribute to
    it (with their signed coefficients) sum to zero as polynomials but are
    nonzero in the factor algebra. These sums are the generators of I.

    The full ideal I = BRC * {generators} * BRC is the two-sided ideal they
    generate. Elements of I have the property:
      - They always vanish at the polynomial (weight) level.
      - The generators themselves also vanish at the RC graph level.
      - But general ideal elements a*g*b need NOT vanish at the RC graph level.

    This class provides:
      - Generator computation and storage
      - Multiplication in BRC followed by generator reduction
      - Analysis tools comparing full vs non-phantom Schubert elements
      - Detection of ideal membership at both generator and polynomial levels
    """

    _id = 0

    def __init__(self, size, domain=None):
        super().__init__(domain=domain)
        self._size = size
        self._brc = BoundedRCFactorAlgebra(domain=domain, post_normalize=False)
        self.zero_monom = self._brc.make_key((), 0)
        self._ID = PhantomQuotientAlgebra._id
        PhantomQuotientAlgebra._id += 1
        self.dtype = type(
            "PhantomQuotientElement",
            (PhantomQuotientElement,),
            {"ring": self},
        )

    def __hash__(self):
        return hash(("PhantomQuotientAlgebra", self._ID, self._size))

    def printing_term(self, key):
        rc = self._brc.key_to_rc_graph(key)
        return PhantomQuotientPrintingTerm(key, rc)

    @property
    def size(self):
        return self._size

    @property
    def brc(self):
        return self._brc

    def _partition_for(self, perm):
        if self._size >= len(perm) - 1:
            return tuple(range(len(perm) - 1, 0, -1))
        return tuple((~(perm.strict_mul_dominant(self._size))).trimcode)

    # --- Raw element construction (no ideal reduction) ---

    def _raw_from_tensor_dict(self, dct, size):
        """Build a PhantomQuotientElement from a tensor dict WITHOUT reducing."""
        accum = {}
        for key, coeff in dct.items():
            if coeff == S.Zero:
                continue
            nkey = self._brc._normalize_key(self._brc.make_key(key, size))
            accum[nkey] = accum.get(nkey, S.Zero) + coeff
        return self.dtype({k: v for k, v in accum.items() if v != S.Zero})

    def _raw_from_dict(self, dct):
        """Build a PhantomQuotientElement from a key dict WITHOUT reducing."""
        accum = {}
        for key, coeff in dct.items():
            if coeff == S.Zero:
                continue
            nkey = self._brc._normalize_key(key)
            accum[nkey] = accum.get(nkey, S.Zero) + coeff
        return self.dtype({k: v for k, v in accum.items() if v != S.Zero})

    # --- Ideal generators ---

    @cache
    def phantom_generators_by_rc(self, perm):
        """Compute individual phantom ideal generators for a permutation.

        For perm w at size n, each phantom RC graph R (with R.perm != w) in
        full_CEM(w, n) contributes one generator: the signed sum of its
        tensor monomials.

        Returns a list of (phantom_rc, generator_element) pairs.
        """
        partition = self._partition_for(perm)
        cem = RCGraph.full_CEM(perm, self._size, partition=partition)
        generators = []
        for rc, cem_dict in cem.items():
            if rc.perm != perm:
                gen = self._raw_from_tensor_dict(cem_dict, self._size)
                if any(v != S.Zero for v in gen.values()):
                    generators.append((rc, gen))
        return generators

    @cache
    def phantom_generators(self, perm):
        """Return just the generator elements (without the phantom RC keys)."""
        return [gen for _, gen in self.phantom_generators_by_rc(perm)]

    @cache
    def all_phantom_generators(self):
        """All phantom ideal generators across all permutations at this size."""
        from schubmult.combinatorics.permutation import Permutation
        all_gens = []
        for perm in Permutation.all_permutations(self._size + 1):
            if perm.inv == 0:
                continue
            all_gens.extend(self.phantom_generators_by_rc(perm))
        return all_gens

    # --- Reduction ---

    def reduce(self, elem):
        """Reduce an element by stripping its weight-vanishing component.

        Groups tensor keys by their squashed RC graph. For each RC graph,
        computes the net coefficient (sum of coefficients of all keys squashing
        to it). Keys whose net contribution vanishes are discarded — these are
        the weight-vanishing components that lie in the ideal.

        For each surviving RC graph, one canonical tensor key (the shortest)
        is kept as representative with the net coefficient.

        This is fast: O(number of keys), no generator enumeration needed.
        """
        if not elem:
            return self.dtype({})

        # Group tensor keys by their squashed RC graph
        rc_groups = {}  # {RCGraph: [(key, coeff), ...]}
        for key, coeff in elem.items():
            if coeff == S.Zero:
                continue
            rc = self._brc.key_to_rc_graph(key)
            if rc not in rc_groups:
                rc_groups[rc] = []
            rc_groups[rc].append((key, coeff))

        # For each group, compute net coefficient and keep canonical representative
        result = {}
        for _rc, entries in rc_groups.items():
            net = sum(c for _, c in entries)
            if net == S.Zero:
                continue
            # Pick the canonical key: shortest (fewest factors), then first seen
            canonical_key = min(entries, key=lambda e: len(e[0]))[0]
            result[canonical_key] = result.get(canonical_key, S.Zero) + net

        return self.dtype({k: v for k, v in result.items() if v != S.Zero})

    def reduce_by_generators(self, elem):
        """Reduce an element by subtracting multiples of phantom generators.

        For each generator g, if any key of g appears in elem, subtract the
        appropriate scalar multiple to eliminate that key.

        This is an ANALYSIS tool — slower than reduce() but operates only
        within span(generators). Useful for measuring how much of an element
        is directly attributable to specific phantom generators vs. arising
        from products a*g*b.
        """
        generators = self.all_phantom_generators()
        if not generators:
            return self.dtype(dict(elem))

        result = dict(elem)
        changed = True
        while changed:
            changed = False
            for _rc, gen in generators:
                for gen_key, gen_coeff in gen.items():
                    if gen_coeff == S.Zero:
                        continue
                    cur = result.get(gen_key, S.Zero)
                    if cur == S.Zero:
                        continue
                    factor = cur / gen_coeff
                    for gk, gc in gen.items():
                        result[gk] = result.get(gk, S.Zero) - factor * gc
                    changed = True
                    break
                if changed:
                    break
        return self.dtype({k: v for k, v in result.items() if v != S.Zero})

    # --- Construction with reduction ---

    def from_dict(self, dct):
        raw = self._raw_from_dict(dct)
        return self.reduce(raw)

    def from_tensor_dict(self, dct, size):
        raw = self._raw_from_tensor_dict(dct, size)
        return self.reduce(raw)

    def __call__(self, key):
        return self.from_dict({self._brc._normalize_key(key): S.One})

    # --- Schubert elements ---

    @cache
    def schub_elem(self, perm, partition=None):
        """Full Schubert element in the quotient (all CEM terms, then reduce)."""
        from schubmult.combinatorics.permutation import Permutation
        perm = Permutation(perm)
        if partition is None:
            partition = self._partition_for(perm)
        cem = RCGraph.full_CEM(perm, self._size, partition=partition)
        result = {}
        for _, cem_dict in cem.items():
            term = self._raw_from_tensor_dict(cem_dict, self._size)
            for k, v in term.items():
                result[k] = result.get(k, S.Zero) + v
        return self.reduce(self.dtype({k: v for k, v in result.items() if v != S.Zero}))

    @cache
    def schub_elem_nonphantom(self, perm, partition=None):
        """Schubert element using only non-phantom CEM terms (then reduce)."""
        from schubmult.combinatorics.permutation import Permutation
        perm = Permutation(perm)
        if partition is None:
            partition = self._partition_for(perm)
        cem = RCGraph.full_CEM(perm, self._size, partition=partition)
        result = {}
        for rc, cem_dict in cem.items():
            if rc.perm != perm:
                continue
            term = self._raw_from_tensor_dict(cem_dict, self._size)
            for k, v in term.items():
                result[k] = result.get(k, S.Zero) + v
        return self.reduce(self.dtype({k: v for k, v in result.items() if v != S.Zero}))

    def schub_elem_raw(self, perm, partition=None):
        """Full Schubert element WITHOUT any reduction (for analysis)."""
        from schubmult.combinatorics.permutation import Permutation
        perm = Permutation(perm)
        if partition is None:
            partition = self._partition_for(perm)
        cem = RCGraph.full_CEM(perm, self._size, partition=partition)
        result = {}
        for _, cem_dict in cem.items():
            term = self._raw_from_tensor_dict(cem_dict, self._size)
            for k, v in term.items():
                result[k] = result.get(k, S.Zero) + v
        return self.dtype({k: v for k, v in result.items() if v != S.Zero})

    # --- Multiplication ---

    def mul_expr(self, a, b):
        """Multiply two quotient elements in the factor algebra, then reduce."""
        if not isinstance(b, PhantomQuotientElement):
            raise TypeError(f"Cannot multiply PhantomQuotientElement by {type(b)}")
        accum = {}
        for left_key, left_coeff in a.items():
            for right_key, right_coeff in b.items():
                key = self._brc._mul_keys(left_key, right_key)
                accum[key] = accum.get(key, S.Zero) + left_coeff * right_coeff
        raw = self.dtype({k: v for k, v in accum.items() if v != S.Zero})
        return self.reduce(raw)

    def mul_raw(self, a, b):
        """Multiply without reducing (for analysis)."""
        accum = {}
        for left_key, left_coeff in a.items():
            for right_key, right_coeff in b.items():
                key = self._brc._mul_keys(left_key, right_key)
                accum[key] = accum.get(key, S.Zero) + left_coeff * right_coeff
        return self.dtype({k: v for k, v in accum.items() if v != S.Zero})

    # --- Ideal membership detection ---

    def vanishes_in_weight(self, elem):
        """Check whether an element vanishes at the polynomial (weight) level.

        All ideal elements vanish in weight. So if this returns False,
        the element is definitely NOT in the ideal.
        """
        r = RCGraphRing()
        rc_elem = r.zero
        for key, coeff in elem.items():
            if coeff == 0:
                continue
            rc = self._brc.key_to_rc_graph(key)
            rc_elem += coeff * r(rc)
        # Evaluate the polynomial; if it's identically zero, the element vanishes in weight
        # For now, check RC graph level cancellation as a proxy
        return all(v == S.Zero for v in rc_elem.values())

    def vanishes_at_rc_level(self, elem):
        """Check whether an element vanishes when squashed to RC graphs.

        Generators vanish at this level. General ideal elements may NOT.
        """
        r = RCGraphRing()
        rc_elem = r.zero
        for key, coeff in elem.items():
            if coeff == 0:
                continue
            rc = self._brc.key_to_rc_graph(key)
            rc_elem += coeff * r(rc)
        return all(v == S.Zero for v in rc_elem.values())

    def squash_to_rc(self, elem):
        """Squash a factor algebra element to the RC graph ring."""
        r = RCGraphRing()
        rc_elem = r.zero
        for key, coeff in elem.items():
            if coeff == 0:
                continue
            rc = self._brc.key_to_rc_graph(key)
            rc_elem += coeff * r(rc)
        return rc_elem

    # --- Analysis tools ---

    def phantom_report(self, perm):
        """Print the phantom generators for a permutation."""
        from schubmult.combinatorics.permutation import Permutation
        perm = Permutation(perm)
        gens = self.phantom_generators_by_rc(perm)
        print(f"Phantom ideal generators for {perm} at size {self._size}")
        print("=" * 60)
        if not gens:
            print("  No phantoms.")
        for i, (phantom_rc, gen) in enumerate(gens):
            print(f"\n  Generator {i+1} (phantom rc.perm={phantom_rc.perm}, "
                  f"weight={phantom_rc.length_vector}):")
            print(f"    {len(gen)} tensor terms:")
            for key, coeff in gen.items():
                squashed = self._brc.key_to_rc_graph(key)
                print(f"      coeff={coeff}, squash_perm={squashed.perm}, "
                      f"#factors={len(key)}")
                for j, factor in enumerate(key):
                    print(f"        factor[{j}]: size={len(factor)}, perm={factor.perm}")
            rc_vanish = self.vanishes_at_rc_level(gen)
            wt_vanish = self.vanishes_in_weight(gen)
            print(f"    Vanishes at RC level: {rc_vanish}")
            print(f"    Vanishes in weight:   {wt_vanish}")
        print("=" * 60)

    def product_comparison(self, perm1, perm2):
        """Compare products of Schubert elements with and without phantoms.

        Shows differences at both the factor algebra level and the RC graph level.
        Highlights the key phenomenon: phantoms can produce differences that
        vanish in weight but NOT at the RC graph level.
        """
        from schubmult.combinatorics.permutation import Permutation
        perm1, perm2 = Permutation(perm1), Permutation(perm2)

        s_u = self.schub_elem(perm1)
        s_v = self.schub_elem(perm2)
        s_u_clean = self.schub_elem_nonphantom(perm1)
        s_v_clean = self.schub_elem_nonphantom(perm2)

        prod_full = self.mul(s_u, s_v)
        prod_clean = self.mul(s_u_clean, s_v_clean)
        prod_mixed_uv = self.mul(s_u, s_v_clean)
        prod_mixed_vu = self.mul(s_u_clean, s_v)

        # Factor algebra difference
        diff_factor = self.sub(prod_full, prod_clean)

        # RC graph level
        rc_full = self.squash_to_rc(prod_full)
        rc_clean = self.squash_to_rc(prod_clean)
        r = RCGraphRing()
        rc_diff = r.from_dict({k: rc_full.get(k, S.Zero) - rc_clean.get(k, S.Zero)
                               for k in set(rc_full) | set(rc_clean)})
        rc_diff = r.from_dict({k: v for k, v in rc_diff.items() if v != S.Zero})

        print(f"Product S_{perm1} * S_{perm2} at size {self._size}")
        print("=" * 60)
        print(f"  Full product:  {len(prod_full)} tensor keys")
        print(f"  Clean product: {len(prod_clean)} tensor keys")
        print(f"  Mixed (u_full, v_clean): {len(prod_mixed_uv)} tensor keys")
        print(f"  Mixed (u_clean, v_full): {len(prod_mixed_vu)} tensor keys")

        print(f"\n  Factor-algebra difference (full - clean): {len(diff_factor)} terms")
        if len(diff_factor) > 0:
            wt_vanish = self.vanishes_in_weight(diff_factor)
            rc_vanish = self.vanishes_at_rc_level(diff_factor)
            print(f"    Vanishes in weight:   {wt_vanish}")
            print(f"    Vanishes at RC level: {rc_vanish}")
            for k, v in diff_factor.items():
                squashed = self._brc.key_to_rc_graph(k)
                print(f"    coeff={v}, squash_perm={squashed.perm}, #factors={len(k)}")
        else:
            print("    (zero — phantoms had no effect)")

        print(f"\n  RC-graph difference: {len(rc_diff)} terms")
        if len(rc_diff) > 0:
            for k, v in rc_diff.items():
                print(f"    perm={RCGraph(k).perm}: {v}")
        else:
            print("    (zero at RC level)")

        print("=" * 60)
        return {
            "full": prod_full,
            "clean": prod_clean,
            "mixed_uv": prod_mixed_uv,
            "mixed_vu": prod_mixed_vu,
            "diff_factor": diff_factor,
            "rc_full": rc_full,
            "rc_clean": rc_clean,
            "rc_diff": rc_diff,
        }
