

# This file was *autogenerated* from the file src/schubmult/_scripts/unlinted/parse_qschub.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1)
import sys

QSym = QuasiSymmetricFunctions(ZZ)
QS = QSym.QS()
M = QSym.M()

lines = []

with open(sys.argv[_sage_const_1 ], "r") as f:
    lines = f.readlines()

for line in lines:
    name, val = line.split(" = ")
    val = eval(val)
    print(f"{name} = {QS(val)}")

