#!/usr/bin/env python
"""Regenerate the Markdown API reference under docs/ from source docstrings.

Usage:
    python docs/generate_docs.py

Reads the shared loader/processor/renderer settings from pydoc-markdown.yml
and applies them once per module (writing docs/modules/<dotted.module>.md,
plus an index at docs/modules/README.md) and once for the whole package
(writing the consolidated docs/API.md).
"""

from __future__ import annotations

from pathlib import Path

from pydoc_markdown import PydocMarkdown
from pydoc_markdown.contrib.loaders.python import PythonLoader
from pydoc_markdown.interfaces import Context

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
DOCS = ROOT / "docs"
CONFIG_FILE = ROOT / "pydoc-markdown.yml"

# Path components that mark research scratch space rather than public API.
EXCLUDED_PARTS = {"unlinted", "__pycache__"}

# Dotted module names backed by an __init__.py (i.e. packages), filled in by discover_modules().
PACKAGE_MODULES: set[str] = set()


def discover_modules() -> list[str]:
    """Dotted module names for every non-excluded file under src/schubmult.

    Also records which of those names are packages (came from __init__.py) into
    PACKAGE_MODULES, so module_rel_path() can place their page at <pkg>/index.md
    instead of a <pkg>.md file sitting beside the <pkg>/ directory.
    """
    modules = []
    PACKAGE_MODULES.clear()
    for path in sorted((SRC / "schubmult").rglob("*.py")):
        rel = path.relative_to(SRC)
        if EXCLUDED_PARTS & set(rel.parts):
            continue
        parts = list(rel.with_suffix("").parts)
        is_package = parts[-1] == "__init__"
        if is_package:
            parts = parts[:-1]
        if not parts:
            continue
        modname = ".".join(parts)
        if is_package:
            PACKAGE_MODULES.add(modname)
        modules.append(modname)
    return modules


def new_session(loader: PythonLoader) -> PydocMarkdown:
    session = PydocMarkdown()
    session.load_config(str(CONFIG_FILE))
    session.loaders = [loader]
    session.init(Context(directory=str(ROOT)))
    return session


def render_module(modname: str, filename: Path) -> None:
    session = new_session(PythonLoader(search_path=["src"], modules=[modname]))
    session.renderer.filename = str(filename)
    filename.parent.mkdir(parents=True, exist_ok=True)
    modules = session.load_modules()
    session.process(modules)
    session.render(modules, run_hooks=False)


def render_consolidated(filename: Path) -> None:
    session = new_session(PythonLoader(search_path=["src"], packages=["schubmult"]))
    session.renderer.filename = str(filename)
    modules = session.load_modules()
    session.process(modules)
    session.render(modules, run_hooks=False)


def module_rel_path(modname: str) -> Path:
    """Nested file path (relative to docs/modules/) for a dotted module name.

    Packages are placed at ``<pkg>/index.md`` (inside their own directory) rather
    than a ``<pkg>.md`` file next to the ``<pkg>/`` directory, so MkDocs'
    ``navigation.indexes`` feature attaches the page to the section instead of
    creating a separate, mostly-empty entry.
    """
    parts = modname.split(".")
    if modname in PACKAGE_MODULES:
        return Path(*parts, "index.md")
    return Path(*parts).with_suffix(".md")


def write_index(module_names: list[str]) -> None:
    lines = [
        "# Module reference",
        "",
        "Generated by `docs/generate_docs.py`; do not edit by hand.",
        "",
    ]
    lines += [f"- [{name}]({module_rel_path(name).as_posix()})" for name in module_names]
    (DOCS / "modules" / "README.md").write_text("\n".join(lines) + "\n")


def main() -> None:
    module_names = discover_modules()
    print(f"Rendering {len(module_names)} per-module pages under docs/modules/ ...")
    for name in module_names:
        render_module(name, DOCS / "modules" / module_rel_path(name))
    write_index(module_names)
    print("Rendering consolidated docs/API.md ...")
    render_consolidated(DOCS / "API.md")
    print("Done.")


if __name__ == "__main__":
    main()
