#!/usr/bin/env python
"""Regenerate the Markdown API reference under docs/ from source docstrings.

Usage:
    python docs/generate_docs.py

Reads the shared loader/processor/renderer settings from pydoc-markdown.yml
and applies them once per module (writing docs/modules/<dotted.module>.md,
plus an index at docs/modules/README.md) and once for the whole package
(writing the consolidated docs/API.md).
"""

from __future__ import annotations

from pathlib import Path

from pydoc_markdown import PydocMarkdown
from pydoc_markdown.contrib.loaders.python import PythonLoader
from pydoc_markdown.interfaces import Context

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
DOCS = ROOT / "docs"
CONFIG_FILE = ROOT / "pydoc-markdown.yml"

# Path components that mark research scratch space rather than public API.
EXCLUDED_PARTS = {"unlinted", "__pycache__"}


def discover_modules() -> list[str]:
    """Dotted module names for every non-excluded file under src/schubmult."""
    modules = []
    for path in sorted((SRC / "schubmult").rglob("*.py")):
        rel = path.relative_to(SRC)
        if EXCLUDED_PARTS & set(rel.parts):
            continue
        parts = list(rel.with_suffix("").parts)
        if parts[-1] == "__init__":
            parts = parts[:-1]
        if not parts:
            continue
        modules.append(".".join(parts))
    return modules


def new_session(loader: PythonLoader) -> PydocMarkdown:
    session = PydocMarkdown()
    session.load_config(str(CONFIG_FILE))
    session.loaders = [loader]
    session.init(Context(directory=str(ROOT)))
    return session


def render_module(modname: str, filename: Path) -> None:
    session = new_session(PythonLoader(search_path=["src"], modules=[modname]))
    session.renderer.filename = str(filename)
    filename.parent.mkdir(parents=True, exist_ok=True)
    modules = session.load_modules()
    session.process(modules)
    session.render(modules, run_hooks=False)


def render_consolidated(filename: Path) -> None:
    session = new_session(PythonLoader(search_path=["src"], packages=["schubmult"]))
    session.renderer.filename = str(filename)
    modules = session.load_modules()
    session.process(modules)
    session.render(modules, run_hooks=False)


def module_rel_path(modname: str) -> Path:
    """Nested file path (relative to docs/modules/) for a dotted module name."""
    return Path(*modname.split(".")).with_suffix(".md")


def write_index(module_names: list[str]) -> None:
    lines = [
        "# Module reference",
        "",
        "Generated by `docs/generate_docs.py`; do not edit by hand.",
        "",
    ]
    lines += [f"- [{name}]({module_rel_path(name).as_posix()})" for name in module_names]
    (DOCS / "modules" / "README.md").write_text("\n".join(lines) + "\n")


def main() -> None:
    module_names = discover_modules()
    print(f"Rendering {len(module_names)} per-module pages under docs/modules/ ...")
    for name in module_names:
        render_module(name, DOCS / "modules" / module_rel_path(name))
    write_index(module_names)
    print("Rendering consolidated docs/API.md ...")
    render_consolidated(DOCS / "API.md")
    print("Done.")


if __name__ == "__main__":
    main()
